# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: "`1"
    replace: |
        translate to Chinese: {{clipb}}
    vars:
      - name: "clipb"
        type: "clipboard"

  - trigger: "`3"
    replace: |
      Hello, I am an elementary school student. Please help me explain the code line by line.I have severe reading difficulties and learning disabilities, along with cognitive and visual problems. It's hard for me to focus or pay attention for long. When I read, I often lose my place or skip lines. I also have trouble understanding the meaning of what I'm reading. Reading makes me feel frustrated or anxious, and I'm not interested in books or other written materials because of these struggles,I don't have much education.Please explain the above content again using very simple and easy-to-understand language.
  
  - trigger: ":7z"
    replace: "7z a -mx=9 -m0=LZMA2 -md=1024m -mfb=273 -ms=on -mmt=2 -mhe=on \".7z\" \"\""

  - trigger: "`2"
    replace: |
      What is the full English name of the keyword here? What's its Chinese translation?

  - trigger: ":ip"
    replace: "ipconfig && python -m http.server 80\n"

  - trigger: ":mpv"
    replace: |
      nohup mpv --shuffle --no-video "$HOME/touhou" &> /dev/null &
      disown
      exit

  - trigger: ":ssh"
    replace: "ssh -p2222 aa@localhost\n"
  
  - trigger: ":codium"
    replace: |
      codium --install-extension vscodevim.vim
      codium --install-extension ms-python.python

  - trigger: ":rmai"
    replace: |
      1. I'm going to give you some information before asking you to write an article. Do you understand?
      2. When it comes to writing content, two factors are crucial, "perplexity" and "burstiness." Perplexity measures the complexity of text. Separately, burstiness compares the variations of sentences. Humans tend to write with great burstiness, for example, with some longer or complex sentences alongside shorter sentences. AI sentences tend to be more uniform. Therefore, when writing the following content I am going to ask you to create, I need it to have a good amount of perplexity and burstiness. Do you understand?
      3. using the concepts written previously, rewrite this article with a high degree of perplexity and burstiness:
      4. Rewrite this article changing 50% of nouns and verbs for similar ones and rewrite verb usages to add natural sounding variations in complexity but retain the same tense and overall meaning.
      Edit: Number 4 was an addition that someone in the comments added that I found useful. I was testing it out, and when following steps 1 - 3 I got within the high range of 80% human made content in the ai detector. But when adding on step 4, it brought it to around 98%. Granted, you have to be careful make sure ChatGPT doesn't add any weird verbs or nouns that don't apply. I always recommend looking through with your own eyes afterward to make sure the text conveys the message you are aiming for. Another thing to note is that I don't think step 4 is ALWAYS necessary. I have gotten 100% human made content without it before. I suggest that you follow steps 1 - 3, see how much ai detects, and THEN use step 4 as necessary if applicable, because it won't always be.

  - trigger: ":update"
    replace: |
      cd $env:USERPROFILE\\marisafreeman.github.io
      git remote set-url --push origin no_push
      git pull origin main
      cp $env:USERPROFILE\\marisafreeman.github.io\\Espanso\\base.yml $env:USERPROFILE\\scoop\\apps\\espanso\\current\\.espanso\\match\\base.yml
      cp $env:USERPROFILE\\marisafreeman.github.io\\nvim\\init.vim $env:USERPROFILE\\AppData\\Local\\nvim\\init.vim
      exit

  - trigger: ":nv"
    replace: "cd / && nvim $(fzf)\n"
