# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  - trigger: ":tr"
    replace: "translate to Chinese:"

  - trigger: ":tbd"
    replace: "看不懂,请用非常详细的通俗易懂的话讲解(尽量不要举例,如果非要举例子,要加上每个例子映射的是什么),我没有什么文化,并且阅读能力非常差,有严重的阅读障碍"

  - trigger: ":gk"
    replace: "kirisamefreeman@gmail.com"

  - trigger: ":7z"
    replace: "7z a -mx=9 -m0=LZMA2 -md=1024m -mfb=273 -ms=on -mmt=2 -mhe=on \".7z\" \"\""

  - trigger: ":ip"
    replace: "ipconfig && python -m http.server 80"

  - trigger: ":mpv"
    replace: "Start-Process mpv -ArgumentList '--shuffle', '--no-video', \"$HOME/touhou\" -WindowStyle Hidden"

  - trigger: ":ub"
    replace: "ssh -p2222 aa@localhost"

  - trigger: ":c7"
    replace: "ssh yangkun_42212346@192.168.216.230"

  - trigger: ":vvim"
    replace: "codium --install-extension vscodevim.vim"

  - trigger: ":vpy"
    replace: "codium --install-extension ms-python.python"
  
  - trigger: ":OOBE"
    replace: "net user administrator /active:yes && oobe\\msoobe && shutdown -r"
  
  - trigger: ":rmai"
    replace: "在要求您写一篇文章之前，我将给您一些信息。您明白吗？

在撰写内容时，有两个因素至关重要，即“困惑度”和“突发性”。困惑度衡量文本的复杂性。另一方面，突发性比较句子的变化。人类倾向于以较大的突发性写作，例如，使用一些较长或复杂的句子与较短的句子并列。人工智能生成的句子往往更为统一。因此，当我要求您创作以下内容时，我需要它具有相当的困惑度和突发性。您明白吗？

使用前面提到的概念，重写这篇文章，要求具有高度的困惑度和突发性：

重写这篇文章,将50%的名词和动词替换为相似的词，并重写动词的用法，以增加自然听起来的复杂性变化，同时保持相同的时态和整体含义。

编辑: 第4步是评论中有人添加的,我觉得很有用。我在测试时,按照步骤1-3进行时,AI检测器中人类生成内容的比例高达80%。但当添加第4步后,这个比例提高到了约98%。当然,您必须小心,确保ChatGPT不会添加任何不适用的奇怪动词或名词。我总是建议之后用自己的眼睛审查,以确保文本传达您想要表达的信息。另一个需要注意的是,我认为第4步并不总是必要的。我之前也有不使用它就获得100%人类生成的内容。我建议您按照步骤1-3进行,看看AI检测的结果,然后根据需要使用第4步,因为并不总是需要的。"

  - trigger: ":test"
    replace: "net user administrator /active:yes && oobe\\msoobe && shutdown -r"
